/*
 * This source file was generated by the Gradle 'init' task
 */
package korea_1_iot_jdbc;

import korea_1_iot_jdbc.main.UserManager;

public class App {
//    public String getGreeting() {
//        return "Hello World!!!!!";
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
    	UserManager userManager = new UserManager();
    	
    	try {
    		userManager.run();
    	} catch (Exception e) {
    		e.printStackTrace();
    	}
    }
}
         