/*
 * This source file was generated by the Gradle 'init' task
 */
package korea_1_iot.jdbc;

import org.junit.jupiter.api.Test;

import korea_1_iot_jdbc.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
